# -*- coding: utf-8 -*-
"""OCR.ipynb

Automatically generated by Colaboratory.

Original file is located at

"""

!pip install opencv-contrib-python
!pip install --upgrade google-cloud-vision
!pip install utils

import os
import io
import numpy as np
import platform
from PIL import ImageFont, ImageDraw, Image
 
import cv2
from google.cloud import vision
from matplotlib import pyplot as plt

!set GOOGLE_APPLICATION_CREDENTIALS=KEY_PATH

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'key_json파일'

client_options = {'api_endpoint':'eu-vision.googleapis.com'}
client = vision.ImageAnnotatorClient(client_options=client_options)

path = '/content/image'
filenames = os.listdir(path)


for filename in filenames:
  if filename[-4:] != '.jpg':
    pass
  else:
    with io.open(path+'/'+filename, 'rb') as image_file:
      print(image_file)
      content = image_file.read()
      print(content)
      

    image = vision.Image(content=content)
    response = client.text_detection(image=image)
    texts = response.text_annotations

